modify script

diff --git a/.github/workflows/misc_md5.yml b/.github/workflows/misc_md5.yml
--- a/.github/workflows/misc_md5.yml
+++ b/.github/workflows/misc_md5.yml
@@ -55,7 +55,7 @@ jobs:
             chmod +x misc_script
             mkdir $FILE_BASE
             export command="bash misc_script"
-            $command || $command  #retry command twice 
+            timeout 5m bash -c '$command || $command'  #retry command twice 
             sed -i '1i [GITHUB ACTION] <misc-aws-md5> weather.sh' $FILE_PATH
             cat $FILE_PATH
         env:
@@ -78,7 +78,7 @@ jobs:
         run: |
             export action_bucket=s3://`echo ${GITHUB_REPOSITORY_OWNER}action | tr "[A-Z]" "[a-z]"`
             export command="python aws/md5_aws.py --files_path=$FILE_BASE 2>/dev/null"
-            files_num=`$command || $command || echo 0` #retry command twice 
+            files_num=`timeout 5m bash -c '$command || $command || echo 0'` #retry command twice 
             echo $files_num
             echo '::set-output name=FILE_NUM::'$files_num
         id: aws-md5
