add timeout to action

diff --git a/.github/workflows/morning_daily.yml b/.github/workflows/morning_daily.yml
--- a/.github/workflows/morning_daily.yml
+++ b/.github/workflows/morning_daily.yml
@@ -43,7 +43,6 @@ jobs:
             pipreqs .
             pip install -r requirements.txt
 
-      - name: Install Playwright
         if: ${{ env.IF_PLAYWRIGHT == 'True'}}
         run: |
             python -m playwright install
@@ -51,7 +50,7 @@ jobs:
       - name: run python downloader
         run: |
             export command="python $MATRIX_SCRIPT 2>/dev/null"
-            $command || $command  #retry command twice 
+            timeout 5m bash -c '$command || $command'  #retry command twice 
         env:
             MATRIX_SCRIPT: ${{matrix.script}}
 
@@ -71,7 +70,8 @@ jobs:
         run: |
             export action_bucket=s3://`echo ${GITHUB_REPOSITORY_OWNER}action | tr "[A-Z]" "[a-z]"`
             export command="python aws/md5_aws.py --files_path=screenshot 2>/dev/null"
-            files_num=`$command || $command || echo 0` #retry command twice 
+            files_num=`timeout 5m bash -c '$command || $command || echo 0'` #retry command twice 
+            echo $files_num
             echo '::set-output name=FILE_NUM::'$files_num
         id: aws-md5
         env:
